device_number: 0
offload_half_layers: False
model_type: "SD3"
use_rf: False
exps:
  -
    exp_name: "single-bench-no-rf-patch"
    dataset_yaml: single-bench.yaml
    sampler_type: "FlowEditSD3"
    T_steps: 50
    n_avg: 1
    src_guidance_scale: []
    tar_guidance_scale: [6.5]
    n_min: 0
    n_max: [50]
    seed: 179
    scene_text_edit: True