device_number: 0
offload_half_layers: False
model_type: "SD3"
exps:
  -
    exp_name: "single-bench-1"
    dataset_yaml: single-bench.yaml
    sampler_type: "FlowEditSD3"
    T_steps: 50
    n_avg: 1
    src_guidance_scale: [1]
    tar_guidance_scale: [3.5, 4.5, 5.5, 6.5, 7, 8, 9.5]
    n_min: 0
    n_max: [28, 29, 30, 31, 32, 33, 34, 35, 36, 38, 39, 40, 41, 42, 43, 44, 46, 48, 50]
    seed: 179
    scene_text_edit: True