device_number: 0
offload_half_layers: False
model_type: "SD3"
exps:
  -
    exp_name: "single-bench"
    dataset_yaml: single-bench.yaml
    sampler_type: "FlowEditSD3"
    T_steps: 50
    n_avg: 1
    src_guidance_scale: [1, 3, 6, 9]
    tar_guidance_scale: [7, 9, 11]
    n_min: 0
    n_max: [25, 30, 35, 38, 40, 43, 45, 47, 48, 50]
    seed: 179
    scene_text_edit: True