device_number: 0
offload_half_layers: False
model_type: "SD3"
use_rf: True
dtc: 16
exps:
  -
    exp_name: "single-bench-4"
    dataset_yaml: single-bench-4.yaml
    sampler_type: "FlowEditSD3"
    T_steps: 50
    n_avg: 1
    src_guidance_scale: [1]
    tar_guidance_scale: [4.5, 6.5, 9.5]
    n_min: 0
    n_max: [35, 36, 38, 37, 39, 40, 41, 42, 43, 44, 46, 47, 48, 49, 50]
    seed: 179
    scene_text_edit: True