- 
  exp_name: "FlowEdit_SD3_norf"
  dataset_yaml: single-bench.yaml
  model_type: "SD3"
  sampler_type: "FlowEditSD3"
  T_steps: 50
  n_avg: 1
  src_guidance_scale: 6.5
  tar_guidance_scale: 6.5
  n_min: 0
  n_max: 50
  seed: 42

