device_number: 0
offload_half_layers: False
model_type: "SD3"
exps:
  -
    exp_name: "single-bench-2"
    dataset_yaml: single-bench-2.yaml
    sampler_type: "FlowEditSD3"
    T_steps: 50
    n_avg: 1
    src_guidance_scale: [1, 3]
    tar_guidance_scale: [4.5, 5.5, 6.5, 7, 7.5, 8, 9.5]
    n_min: 0
    n_max: [30, 31, 32, 33, 34, 35, 36, 38, 39, 40, 41, 42, 43, 44, 46, 48, 50]
    seed: 179
    scene_text_edit: True