device_number: 0
offload_half_layers: True
model_type: "SD3"
exps:
  -
    exp_name: "CFG1-1"
    dataset_yaml: anytext-bench.yaml
    sampler_type: "FlowEditSD3"
    T_steps: 50
    n_avg: 1
    src_guidance_scale: 1
    tar_guidance_scale: 1
    n_min: 0
    n_max: 50
    seed: 179
    scene_text_edit: True

