device_number: 0
offload_half_layers: False
model_type: "SD3"
exps:
  -
    exp_name: "single-bench"
    dataset_yaml: single-bench.yaml
    sampler_type: "FlowEditSD3"
    T_steps: 50
    n_avg: 1
    src_guidance_scale: [1, 2, 3, 6, 7]
    tar_guidance_scale: [5, 6, 6.5, 7, 7.5, 8, 8.5]
    n_min: 0
    n_max: [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 38, 40, 42, 44, 45, 46, 47, 48, 49, 50]
    seed: 179
    scene_text_edit: True