device_number: 0
offload_half_layers: False
model_type: "SD3"
use_rf: True
dtc: 2
v_cache_mode: "lv"
exps:
  -
    exp_name: "single-bench-2"
    dataset_yaml: single-bench-2.yaml
    sampler_type: "FlowEditSD3"
    T_steps: 50
    n_avg: 1
    src_guidance_scale: []
    tar_guidance_scale: [4.5, 6.5]
    patch_v_layers: [0, 1, 2, 5, 13]
    patch_v_steps: [0, 1, 2, 5, 10]
    n_min: 0
    n_max: [48, 50]
    seed: 179
    scene_text_edit: True